### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by MiroK** [MiroK/sl-pde#1]
- [x] make a structured probe for FEniCS data. This should be an alternative to storing the entire fem fields
- [ ] time derivatives of data (fields, structured)
- [ ] spatial derivatives of structured data (see the sparse learning paper)
- [ ] with 1-3 pieces in place put together the toolchain. Note that probing point can be anywhere inside the probed region
- [ ] test the toolchain on simple FEniCS examples
- [ ] use with Basilisk
